region: "fr-par"
secret_var1: "value1"
secret_var2: "value2"
secret_varA: "valueA"
secret_varB: "valueB"
var2: "" # this one will be set using module "env" variable; we set it here so the validator doesn't complain

project_id: "00000000-0000-0000-0000-000000000000" # replace with a valid project id before applying!
