region: "fr-par"
secret_var1: "value1"
secret_var2: "value2"
secret_varA: "valueA"
secret_varB: "valueB"
var2: "env_var_var2_value"

project_id: "00000000-0000-0000-0000-000000000000" # replace with a valid project id before applying!
